name: "Hello World Workflow"

on: 
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  hello_world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Printing Hello World
        run: echo "Hello World"
      
